-- MySQL Script generated by MySQL Workbench
-- Sat Apr 13 22:24:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Editorial` (
  `idEditorial` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idEditorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(80) NOT NULL,
  `Apellido` VARCHAR(80) NOT NULL,
  `Nacionalidad` VARCHAR(50) NOT NULL,
  `Libros` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` CHAR(2) NOT NULL,
  `Departamento` VARCHAR(25) NOT NULL,
  `Pais` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Municipios` (
  `idMunicipios` CHAR(3) NOT NULL,
  `Municipios` VARCHAR(50) NOT NULL,
  `idDepartamento` VARCHAR(2) NOT NULL,
  `Departamento_idDepartamento` CHAR(2) NOT NULL,
  PRIMARY KEY (`idMunicipios`),
  CONSTRAINT `fk_Municipios_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Municipios_Departamento1_idx` ON `mydb`.`Municipios` (`Departamento_idDepartamento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Distritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Distritos` (
  `idDistritos` CHAR(3) NOT NULL,
  `Distritos` VARCHAR(50) NOT NULL,
  `idDepartamento` CHAR(2) NOT NULL,
  `Municipios_idMunicipios` CHAR(3) NOT NULL,
  PRIMARY KEY (`idDistritos`),
  CONSTRAINT `fk_Distritos_Municipios1`
    FOREIGN KEY (`Municipios_idMunicipios`)
    REFERENCES `mydb`.`Municipios` (`idMunicipios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Distritos_Municipios1_idx` ON `mydb`.`Distritos` (`Municipios_idMunicipios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direcciones` (
  `idDirecciones` INT NOT NULL AUTO_INCREMENT,
  `Linea1` VARCHAR(100) NOT NULL,
  `Linea2` VARCHAR(50) NOT NULL,
  `idDistrito` CHAR(5) NOT NULL,
  `codigoPostal` VARCHAR(7) NOT NULL,
  `Distritos_idDistritos` CHAR(3) NOT NULL,
  PRIMARY KEY (`idDirecciones`),
  CONSTRAINT `fk_Direcciones_Distritos1`
    FOREIGN KEY (`Distritos_idDistritos`)
    REFERENCES `mydb`.`Distritos` (`idDistritos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Direcciones_Distritos1_idx` ON `mydb`.`Direcciones` (`Distritos_idDistritos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Lector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lector` (
  `idLector` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NombresLector` VARCHAR(80) NOT NULL,
  `Apellidos` VARCHAR(80) NOT NULL,
  `Genero` ENUM('Femenino', 'Masculino') NOT NULL,
  `Telefono` INT NOT NULL,
  `Correo` VARCHAR(50) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Direcciones_idDirecciones` INT NOT NULL,
  PRIMARY KEY (`idLector`),
  CONSTRAINT `fk_Lector_Direcciones1`
    FOREIGN KEY (`Direcciones_idDirecciones`)
    REFERENCES `mydb`.`Direcciones` (`idDirecciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Lector_Direcciones1_idx` ON `mydb`.`Lector` (`Direcciones_idDirecciones` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `idCargo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NombreCargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NombresEmpleado` VARCHAR(80) NOT NULL,
  `Apellidos` VARCHAR(80) NOT NULL,
  `idCargo` INT NOT NULL,
  `Correo` VARCHAR(50) NOT NULL,
  `Contraseña` VARCHAR(50) NOT NULL,
  `Direcciones_idDirecciones` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  CONSTRAINT `fk_Administrador_Cargo1`
    FOREIGN KEY (`idCargo`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Direcciones1`
    FOREIGN KEY (`Direcciones_idDirecciones`)
    REFERENCES `mydb`.`Direcciones` (`idDirecciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Administrador_Cargo1_idx` ON `mydb`.`Empleado` (`idCargo` ASC) VISIBLE;

CREATE INDEX `fk_Empleado_Direcciones1_idx` ON `mydb`.`Empleado` (`Direcciones_idDirecciones` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prestamos` (
  `idPrestamos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idLibro` INT NOT NULL,
  `idLector` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idPrestamos`),
  CONSTRAINT `fk_Prestamos_Libro1`
    FOREIGN KEY (`idLibro`)
    REFERENCES `mydb`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamos_Usuario1`
    FOREIGN KEY (`idLector`)
    REFERENCES `mydb`.`Lector` (`idLector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamos_Administrador1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Prestamos_Libro1_idx` ON `mydb`.`Prestamos` (`idLibro` ASC) VISIBLE;

CREATE INDEX `fk_Prestamos_Usuario1_idx` ON `mydb`.`Prestamos` (`idLector` ASC) VISIBLE;

CREATE INDEX `fk_Prestamos_Administrador1_idx` ON `mydb`.`Prestamos` (`idEmpleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`DetallePrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DetallePrestamo` (
  `idDetallePrestamo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idPrestamo` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`idDetallePrestamo`),
  CONSTRAINT `fk_DetallePrestamo_Prestamos1`
    FOREIGN KEY (`idPrestamo`)
    REFERENCES `mydb`.`Prestamos` (`idPrestamos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DetallePrestamo_Prestamos1_idx` ON `mydb`.`DetallePrestamo` (`idPrestamo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libro` (
  `idLibro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idAutor` INT NOT NULL,
  `idEditorial` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  `NombreLibro` VARCHAR(80) NOT NULL,
  `FechaLanzamiento` DATETIME NOT NULL,
  `idDetalleLibro` INT NOT NULL,
  `DetallePrestamo_idDetallePrestamo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idLibro`),
  CONSTRAINT `fk_Libro_Categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_Editorial1`
    FOREIGN KEY (`idEditorial`)
    REFERENCES `mydb`.`Editorial` (`idEditorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_Autor1`
    FOREIGN KEY (`idAutor`)
    REFERENCES `mydb`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_DetallePrestamo1`
    FOREIGN KEY (`DetallePrestamo_idDetallePrestamo`)
    REFERENCES `mydb`.`DetallePrestamo` (`idDetallePrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Libro_Categoria_idx` ON `mydb`.`Libro` (`idCategoria` ASC) VISIBLE;

CREATE INDEX `fk_Libro_Editorial1_idx` ON `mydb`.`Libro` (`idEditorial` ASC) VISIBLE;

CREATE INDEX `fk_Libro_Autor1_idx` ON `mydb`.`Libro` (`idAutor` ASC) VISIBLE;

CREATE INDEX `fk_Libro_DetallePrestamo1_idx` ON `mydb`.`Libro` (`DetallePrestamo_idDetallePrestamo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Mora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mora` (
  `idMora` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idLector` INT NOT NULL,
  `FechaVencimiento` DATETIME NOT NULL,
  `Dias Vencidos` DECIMAL NOT NULL,
  `idPrestamo` INT NOT NULL,
  `Monto de Mora` DECIMAL NOT NULL,
  PRIMARY KEY (`idMora`),
  CONSTRAINT `fk_Mora_Prestamos1`
    FOREIGN KEY (`idPrestamo`)
    REFERENCES `mydb`.`Prestamos` (`idPrestamos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mora_Usuario1`
    FOREIGN KEY (`idLector`)
    REFERENCES `mydb`.`Lector` (`idLector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Mora_Prestamos1_idx` ON `mydb`.`Mora` (`idPrestamo` ASC) VISIBLE;

CREATE INDEX `fk_Mora_Usuario1_idx` ON `mydb`.`Mora` (`idLector` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
